# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :test_and_build do
    scan(
      clean: true,
      project: './MultiCalculator.xcodeproj',
      scheme: 'MultiCalculatorTests',
      device: "iPhone 11 Pro"
    )
  end

  lane :all_certificates do
    ios_identifier = "com.tomoki-sun.app.ios.multi-calculator"
    macOS_identifier = "com.tomoki-sun.app.macOS.multi-calculator"

    match(
      type: "adhoc",
      app_identifier: [ios_identifier, macOS_identifier],
      readonly: true
    )

    match(
      type: "appstore",
      app_identifier: [ios_identifier, macOS_identifier],
      readonly: true
    )

    match(
      type: "development",
      app_identifier: [ios_identifier, macOS_identifier],
      readonly: true
    )
  end
end
